(function(){
const $=(s)=>document.querySelector(s); const app=$('#app');
const gear={
 pickups:['Single coil','Humbucker','P90','Active pickups','Acoustic pickup'],
 guitars:['Fender Stratocaster','Fender Telecaster','Gibson Les Paul','Gibson SG','Gibson ES-335','PRS Custom 24','Ibanez RG','Ibanez JEM','Jackson Soloist','ESP LTD EC-1000','Schecter Hellraiser','Gretsch White Falcon','Martin D-28','Taylor 814ce'],
 amps:['Fender Twin Reverb','Fender Deluxe Reverb','Vox AC30','Marshall Plexi','Marshall JCM800','Marshall DSL','Mesa Boogie Dual Rectifier','Peavey 5150','EVH 5150III','Orange Rockerverb','Soldano SLO-100','Roland JC-120','Boss Katana','Line 6 Helix Amp Model'],
 cabs:['Fender 1x12 Open Back','Fender 2x12 Open Back','Vox 2x12','Marshall 4x12 Greenback','Marshall 4x12 V30','Mesa 4x12 Rectifier','Orange PPC412','1x12 Practice Cab','2x12 Modern Cab','4x12 Metal Cab'],
 pedals:['Boss TU-3 Tuner','Boss SD-1 Super OverDrive','Ibanez Tube Screamer','Klon Centaur','Fulltone OCD','Pro Co RAT','Boss DS-1 Distortion','Boss Metal Zone','Electro-Harmonix Big Muff','Dunlop Cry Baby Wah','MXR Dyna Comp','Boss NS-2 Noise Suppressor','MXR Phase 90','Electro-Harmonix Small Clone','Boss CE-2 Chorus','Boss BF-2 Flanger','Boss DD-7 Delay','Strymon Timeline','Strymon BigSky','Electro-Harmonix Holy Grail Reverb','MXR 10-Band EQ','Digitech Whammy']
};
const presets=['Metallica Rhythm','Metallica Clean','Van Halen Brown Sound','Nirvana Grunge','Green Day Punk','AC/DC Classic Rock','Guns N’ Roses Lead','John Mayer Clean Blues','Pink Floyd Ambient Lead','Worship Clean','Modern Metal','80s Metal','Doom Fuzz','Funk Clean'];
const load=(k,f)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}}; const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let state={tab:'Gear Profile',error:'',adapt:'',mode:'riff',profile:load('gearProfile',{pickupType:gear.pickups[0]}),tone:load('tone',{name:'My Tone',guitar:gear.guitars[0],amp:gear.amps[0],cab:gear.cabs[0],ampSettings:{gain:.5,volume:.7,bass:.5,mid:.5,treble:.5,presence:.5},pedals:[],inputGain:.5}),saved:load('savedTones',[])};
let ctx=null,nodes=[],stream=null;
function render(){app.innerHTML=`<h1>Tone Forge (No-Build)</h1><p class='small'>Works from file://. No React, Vite, imports, or npm required.</p><div class='tabs'>${['Gear Profile','Tone Builder','Presets','Test Audio'].map(t=>`<button class='${state.tab===t?'active':''}' data-tab='${t}'>${t}</button>`).join('')}</div><div id='view'></div><h3>Saved Tones</h3><div>${state.saved.map((s,i)=>`<div class='row'><button data-load='${i}'>${s.name}</button><button data-del='${i}'>Delete</button></div>`).join('')}</div><footer>Gear names are used for reference only. This app is not affiliated with or endorsed by any gear manufacturer.</footer>`; bind(); view();}
function bind(){app.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});app.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{state.tone=state.saved[+b.dataset.load].tone;save('tone',state.tone);render()});app.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{state.saved.splice(+b.dataset.del,1);save('savedTones',state.saved);render()})}
function view(){const v=$('#view'); if(state.tab==='Gear Profile'){v.innerHTML=`<div class='grid'><input id='gtr' placeholder='Guitar they own' value='${state.profile.ownedGuitar||''}'/><select id='pick'>${gear.pickups.map(p=>`<option ${state.profile.pickupType===p?'selected':''}>${p}</option>`).join('')}</select><input id='amp' placeholder='Amp they own' value='${state.profile.ownedAmp||''}'/><input id='ped' placeholder='Pedals they own' value='${state.profile.ownedPedals||''}'/><input id='cab' placeholder='Speaker/cab size' value='${state.profile.cabSize||''}'/><textarea id='notes' placeholder='Notes'>${state.profile.notes||''}</textarea></div><button id='savep'>Save Profile</button>`; $('#savep').onclick=()=>{state.profile={ownedGuitar:$('#gtr').value,pickupType:$('#pick').value,ownedAmp:$('#amp').value,ownedPedals:$('#ped').value,cabSize:$('#cab').value,notes:$('#notes').value};save('gearProfile',state.profile)}}
if(state.tab==='Tone Builder'){v.innerHTML=`<div class='grid'><select id='tg'>${gear.guitars.map(g=>`<option ${state.tone.guitar===g?'selected':''}>${g}</option>`).join('')}</select><select id='ta'>${gear.amps.map(a=>`<option ${state.tone.amp===a?'selected':''}>${a}</option>`).join('')}</select><select id='tc'>${gear.cabs.map(c=>`<option ${state.tone.cab===c?'selected':''}>${c}</option>`).join('')}</select></div><div class='chain'>Input → ${state.tone.pedals.map(p=>p.name).join(' → ')||'No pedals'} → Amp → Cab → Output</div><div class='card'>${['gain','volume','bass','mid','treble','presence'].map(k=>`${k}<input type='range' min='0' max='1' step='0.01' id='${k}' value='${state.tone.ampSettings[k]}'/>`).join('')}</div><div class='row'><select id='addp'><option>Add pedal</option>${gear.pedals.map(p=>`<option>${p}</option>`).join('')}</select><button id='adapt'>Adapt Tone To My Gear</button><button id='savet'>Save Tone</button></div><div>${state.tone.pedals.map((p,i)=>`<div class='card'>${p.name} <button data-up='${i}'>↑</button><button data-down='${i}'>↓</button><button data-rm='${i}'>Remove</button></div>`).join('')}</div>${state.adapt?`<div class='notice'>${state.adapt}</div>`:''}`;
$('#tg').onchange=e=>{state.tone.guitar=e.target.value;save('tone',state.tone)};$('#ta').onchange=e=>{state.tone.amp=e.target.value;save('tone',state.tone)};$('#tc').onchange=e=>{state.tone.cab=e.target.value;save('tone',state.tone)};
['gain','volume','bass','mid','treble','presence'].forEach(k=>$('#'+k).oninput=e=>{state.tone.ampSettings[k]=+e.target.value;save('tone',state.tone)});
$('#addp').onchange=e=>{if(e.target.selectedIndex>0){state.tone.pedals.push({name:e.target.value});save('tone',state.tone);render()}};
$('#adapt').onclick=adapt;$('#savet').onclick=()=>{const n=prompt('Tone name','My Tone');if(!n)return;state.saved.push({name:n,tone:JSON.parse(JSON.stringify(state.tone))});save('savedTones',state.saved);render()};
v.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{state.tone.pedals.splice(+b.dataset.rm,1);save('tone',state.tone);render()});
v.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{const i=+b.dataset.up;if(i>0){const p=state.tone.pedals;[p[i-1],p[i]]=[p[i],p[i-1]];save('tone',state.tone);render()}});
v.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>{const i=+b.dataset.down;const p=state.tone.pedals;if(i<p.length-1){[p[i+1],p[i]]=[p[i],p[i+1]];save('tone',state.tone);render()}})}
if(state.tab==='Presets'){v.innerHTML=`<div class='grid'>${presets.map(n=>`<button data-pre='${n}'>${n}</button>`).join('')}</div>`;v.querySelectorAll('[data-pre]').forEach(b=>b.onclick=()=>{state.tone.name=b.dataset.pre;state.tab='Tone Builder';save('tone',state.tone);render()})}
if(state.tab==='Test Audio'){v.innerHTML=`<div class='row'><label><input type='radio' name='m' ${state.mode==='riff'?'checked':''} value='riff'/>Test Riff</label><label><input type='radio' name='m' ${state.mode==='live'?'checked':''} value='live'/>Live Input</label></div><div class='row'><button id='play'>Play Test Riff</button><button id='stop'>Stop</button></div>${state.error?`<div class='error'>${state.error}</div>`:''}<p class='small'>Live input may require localhost/HTTPS in some browsers.</p>`;
v.querySelectorAll('input[name=m]').forEach(r=>r.onchange=e=>state.mode=e.target.value);$('#play').onclick=()=>state.mode==='riff'?playRiff():startLive();$('#stop').onclick=stopAudio}
}
function adapt(){const p=(state.profile.pickupType||'').toLowerCase();const own=(state.profile.ownedPedals||'').toLowerCase();const c=[];if(p.includes('humbucker')){state.tone.ampSettings.gain-=.08;state.tone.ampSettings.treble+=.06;state.tone.ampSettings.presence+=.05;state.tone.ampSettings.bass-=.05;c.push('Humbuckers: lowered gain, added treble/presence, reduced bass.')}if(p.includes('single')){state.tone.ampSettings.gain+=.06;state.tone.ampSettings.treble-=.05;state.tone.ampSettings.mid+=.08;c.push('Single coils: added gain/mids and softened treble.')}if(p.includes('p90')){state.tone.ampSettings.mid+=.08;state.tone.ampSettings.treble-=.04;c.push('P90: boosted mids and smoothed highs; use a light noise gate.')}if(p.includes('active')){state.tone.inputGain=Math.max(.2,state.tone.inputGain-.1);state.tone.ampSettings.gain-=.07;state.tone.ampSettings.bass-=.06;c.push('Active pickups: lowered input and tightened bass.')}if(p.includes('acoustic')){state.tone.ampSettings.gain=.2;c.push('Acoustic pickup: clean amp preference, lower distortion, add compression/reverb.')}if((state.profile.cabSize||'').toLowerCase().includes('practice')){state.tone.ampSettings.bass-=.08;state.tone.ampSettings.mid+=.1;c.push('Practice amp/cab: reduce bass, add mids, lower gain.')}if(!own.includes('delay'))c.push('No delay pedal listed: use app delay.');if(!own.includes('reverb'))c.push('No reverb pedal listed: use app reverb.');Object.keys(state.tone.ampSettings).forEach(k=>state.tone.ampSettings[k]=Math.max(0,Math.min(1,state.tone.ampSettings[k])));state.adapt=c.join(' ');save('tone',state.tone);render()}
async function ensure(){if(!ctx)ctx=new (window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')await ctx.resume();return ctx}
function stopAudio(){nodes.forEach(n=>{try{n.disconnect()}catch(e){}});nodes=[];if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
async function playRiff(){try{state.error='';stopAudio();const c=await ensure();const out=c.createGain();out.gain.value=.35;out.connect(c.destination);nodes.push(out);[110,147,165,196,220,196].forEach((f,i)=>{const t=c.currentTime+i*.25,o=c.createOscillator(),g=c.createGain();o.type='sawtooth';o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.28,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+.2);o.connect(g);g.connect(out);o.start(t);o.stop(t+.21);nodes.push(o,g)})}catch(e){state.error='Audio error: '+e.message;render()}}
async function startLive(){try{state.error='';if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)throw new Error('getUserMedia not available in this context/browser.');stopAudio();const c=await ensure();stream=await navigator.mediaDevices.getUserMedia({audio:true});const src=c.createMediaStreamSource(stream);const gain=c.createGain();gain.gain.value=.8;src.connect(gain);gain.connect(c.destination);nodes.push(src,gain)}catch(e){state.error='Live input failed: '+e.message;render()}}
render();
})();
